-- first solution
SELECT CONCAT(MAX(EARNINGS),'  ',COUNT(EARNINGS))
FROM (SELECT MONTHS*SALARY AS EARNINGS FROM Employee) AS EMP
GROUP BY EARNINGS
ORDER BY EARNINGS DESC
LIMIT 1;

-- second solution
SELECT MAX(SALARY*MONTHS), COUNT(*)
FROM EMPLOYEE
WHERE (SALARY*MONTHS) = (SELECT MAX(SALARY*MONTHS)
                         FROM EMPLOYEE);
